---
- name: Converge
  hosts: all
  become: true
  
  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"
      changed_when: false
    
    # Skip yum cache update as it's not necessary for testing and can cause issues
    - name: Skip yum cache update for testing
      debug:
        msg: "Skipping yum cache update for container testing"
      when: ansible_os_family == "RedHat"
    
    - name: Install required packages (Debian)
      package:
        name:
          - procps
        state: present
      when: ansible_os_family == "Debian"
    
    - name: Install required packages (RedHat)
      shell: yum install -y procps-ng
      when: ansible_os_family == "RedHat"
      changed_when: false
    
    - name: Create mock tomcat directories
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - /opt/tomcat
        - /opt/tomcat/bin
    
    - name: Create mock tomcat setenv.sh script
      copy:
        dest: /opt/tomcat/bin/setenv.sh
        content: |
          #!/bin/bash
          # Mock setenv.sh for testing
          export JAVA_OPTS=""
        mode: '0755'
        force: no
    
    - name: Create mock systemd directory
      file:
        path: /etc/systemd/system
        state: directory
        mode: '0755'
    
    - name: Create mock tomcat service file
      copy:
        dest: /etc/systemd/system/tomcat.service
        content: |
          [Unit]
          Description=Mock Tomcat Service for Testing
          
          [Service]
          Type=simple
          ExecStart=/bin/sleep infinity
          ExecReload=/bin/true
          
          [Install]
          WantedBy=multi-user.target
        mode: '0644'
  
  tasks:
    - name: "Include contrast.security.agent role"
      include_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
      vars:
        contrast_agent_enabled: true
        contrast_service_name: "tomcat"
        contrast_config_method: "setenv"
        contrast_agent_version: "6.19.0"
        contrast_test_mode: true
        contrast_security_config:
          api:
            url: "https://app.contrastsecurity.com/Contrast"
            api_key: "test-api-key"
            service_key: "test-service-key"
            user_name: "test-user"
          application:
            name: "molecule-test-app"
            tags: "env:test,molecule:true"
          server:
            name: "molecule-test-server"
            environment: "test"
