FROM amazonlinux:2023
RUN yum update -y && yum install -y \
    python3 \
    python3-pip \
    sudo \
    systemd \
    procps \
    ca-certificates \
    && yum clean all \
    && python3 --version
CMD ["/bin/bash", "-c", "while true; do sleep 30; done"]
