---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ubuntu2004
    image: ubuntu:20.04
    pre_build_image: false
    privileged: true
    dockerfile: |
      FROM ubuntu:20.04
      ENV DEBIAN_FRONTEND=noninteractive
      RUN apt-get update && apt-get install -y \
          python3 \
          python3-apt \
          sudo \
          systemd \
          procps \
          curl \
          ca-certificates \
          && rm -rf /var/lib/apt/lists/* \
          && ln -sf /usr/bin/python3 /usr/bin/python
      CMD ["/bin/bash", "-c", "while true; do sleep 30; done"]

provisioner:
  name: ansible
  inventory:
    host_vars:
      ubuntu2004:
        ansible_python_interpreter: /usr/bin/python3
  
  config_options:
    defaults:
      callbacks_enabled: profile_tasks
      stdout_callback: yaml
      roles_path: /Users/jonathanharper/MCP/contrast.security/roles

verifier:
  name: ansible

scenario:
  name: default
  test_sequence:
    - dependency
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - destroy
