---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ubuntu2004
    image: ubuntu:20.04
    pre_build_image: false
    dockerfile: Dockerfile.ubuntu2004
    privileged: true
  
  - name: amazonlinux2
    image: amazonlinux:2
    pre_build_image: false
    dockerfile: Dockerfile.amazonlinux2
    privileged: true

provisioner:
  name: ansible
  inventory:
    host_vars:
      ubuntu2004:
        ansible_python_interpreter: /usr/bin/python3
      amazonlinux2:
        ansible_python_interpreter: /usr/bin/python3
  
  config_options:
    defaults:
      callbacks_enabled: profile_tasks
      stdout_callback: yaml
      roles_path: /Users/jonathanharper/MCP/contrast.security/roles

verifier:
  name: ansible

scenario:
  name: default
  test_sequence:
    - dependency
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - destroy
