---
- name: Verify
  hosts: all
  become: true
  gather_facts: true
  
  tasks:
    - name: Check if Contrast agent JAR exists
      stat:
        path: /opt/contrast/contrast.jar
      register: agent_jar
    
    - name: Assert agent JAR was downloaded
      assert:
        that:
          - agent_jar.stat.exists
          - agent_jar.stat.isreg
        fail_msg: "Contrast agent JAR not found at expected location"
        success_msg: "Contrast agent JAR successfully downloaded"
    
    - name: Check systemd override file
      stat:
        path: /etc/systemd/system/tomcat.service.d/10-contrast.conf
      register: override_file
      when: contrast_config_method | default('setenv') == 'systemd'
    
    - name: Assert override file exists
      assert:
        that:
          - override_file.stat.exists
          - override_file.stat.isreg
        fail_msg: "Systemd override file not found"
        success_msg: "Systemd override file created successfully"
      when: contrast_config_method | default('setenv') == 'systemd'
    
    - name: Read override file content
      slurp:
        src: /etc/systemd/system/tomcat.service.d/10-contrast.conf
      register: override_content
      when: contrast_config_method | default('setenv') == 'systemd'
    
    - name: Decode and check override content
      set_fact:
        override_text: "{{ override_content.content | b64decode }}"
      when: contrast_config_method | default('setenv') == 'systemd'
    
    - name: Assert override contains javaagent
      assert:
        that:
          - "'-javaagent:/opt/contrast/contrast.jar' in override_text"
          - "'JAVA_TOOL_OPTIONS' in override_text"
        fail_msg: "Override file doesn't contain expected javaagent configuration"
        success_msg: "Override file correctly configured"
      when: contrast_config_method | default('setenv') == 'systemd'
    
    - name: Check setenv.sh file
      stat:
        path: /opt/tomcat/bin/setenv.sh
      register: setenv_file
      when: contrast_config_method | default('setenv') == 'setenv'
    
    - name: Assert setenv.sh file exists
      assert:
        that:
          - setenv_file.stat.exists
          - setenv_file.stat.isreg
        fail_msg: "setenv.sh file not found"
        success_msg: "setenv.sh file exists"
      when: contrast_config_method | default('setenv') == 'setenv'
    
    - name: Read setenv.sh content
      slurp:
        src: /opt/tomcat/bin/setenv.sh
      register: setenv_content
      when: contrast_config_method | default('setenv') == 'setenv'
    
    - name: Decode and check setenv.sh content
      set_fact:
        setenv_text: "{{ setenv_content.content | b64decode }}"
      when: contrast_config_method | default('setenv') == 'setenv'
    
    - name: Assert setenv.sh contains javaagent
      assert:
        that:
          - "'-javaagent:/opt/contrast/contrast.jar' in setenv_text"
        fail_msg: "setenv.sh doesn't contain expected javaagent configuration"
        success_msg: "setenv.sh correctly configured"
      when: contrast_config_method | default('setenv') == 'setenv'
    
    - name: Check if service is running (skip for container testing)
      debug:
        msg: "Skipping service check for container testing"
    
    - name: Test idempotency - run role again
      include_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
      vars:
        contrast_agent_enabled: true
        contrast_service_name: "tomcat"
        contrast_config_method: "setenv"
        contrast_test_mode: true
        contrast_agent_version: "6.19.0"
        contrast_security_config:
          api:
            url: "https://app.contrastsecurity.com/Contrast"
            api_key: "test-api-key"
            service_key: "test-service-key"
            user_name: "test-user"
      register: second_run
    
    - name: Assert role is idempotent
      assert:
        that:
          - not second_run.changed
        fail_msg: "Role is not idempotent"
        success_msg: "Role is idempotent"
    
    - name: Test deactivation
      include_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
      vars:
        contrast_agent_enabled: false
        contrast_service_name: "tomcat"
        contrast_config_method: "setenv"
        contrast_test_mode: true
    
    - name: Check setenv.sh file after deactivation
      stat:
        path: /opt/tomcat/bin/setenv.sh
      register: setenv_after_deactivation
      when: contrast_config_method | default('setenv') == 'setenv'
    
    - name: Read setenv.sh content after deactivation
      slurp:
        src: /opt/tomcat/bin/setenv.sh
      register: setenv_content_after
      when: contrast_config_method | default('setenv') == 'setenv' and setenv_after_deactivation.stat.exists
    
    - name: Decode setenv.sh content after deactivation
      set_fact:
        setenv_text_after: "{{ setenv_content_after.content | b64decode }}"
      when: contrast_config_method | default('setenv') == 'setenv' and setenv_after_deactivation.stat.exists
    
    - name: Assert javaagent was removed from setenv.sh
      assert:
        that:
          - "'-javaagent:/opt/contrast/contrast.jar' not in setenv_text_after"
        fail_msg: "javaagent configuration not removed from setenv.sh"
        success_msg: "javaagent configuration successfully removed"
      when: contrast_config_method | default('setenv') == 'setenv' and setenv_after_deactivation.stat.exists
    
    - name: Check override file removed
      stat:
        path: /etc/systemd/system/tomcat.service.d/10-contrast.conf
      register: override_removed
      when: contrast_config_method | default('setenv') == 'systemd'
    
    - name: Assert override was removed
      assert:
        that:
          - not override_removed.stat.exists
        fail_msg: "Override file was not removed during deactivation"
        success_msg: "Override file successfully removed"
      when: contrast_config_method | default('setenv') == 'systemd'
